In [33]:
import pandas as pd 

df = pd.read_json("nested_orders.json")
df["customer"].head()

0    {'customer_id': 501, 'name': 'Rahul', 'city': ...
1    {'customer_id': 502, 'name': 'Priya', 'city': ...
2    {'customer_id': 503, 'name': 'Amit', 'city': '...
3    {'customer_id': 504, 'name': 'Neha', 'city': '...
Name: customer, dtype: object

In [34]:
customer_df = pd.json_normalize(df["customer"])
customer_df.head()

   customer_id   name    city
0          501  Rahul    Pune
1          502  Priya  Mumbai
2          503   Amit   Delhi
3          504   Neha    Pune

In [35]:
combined_df = pd.concat([df,customer_df],axis = 1)

In [36]:
combined_df

,order_id,order_date,customer,items,customer_id,name,city
0,1001,2026-10-01,"{'customer_id': 501, 'name': 'Rahul', 'city': ...","[{'product_id': 'P101', 'product_name': 'Lapto...",501,Rahul,Pune
1,1002,2026-10-02,"{'customer_id': 502, 'name': 'Priya', 'city': ...","[{'product_id': 'P103', 'product_name': 'Keybo...",502,Priya,Mumbai
2,1003,2026-10-02,"{'customer_id': 503, 'name': 'Amit', 'city': '...","[{'product_id': 'P104', 'product_name': 'Phone...",503,Amit,Delhi
3,1004,2026-10-03,"{'customer_id': 504, 'name': 'Neha', 'city': '...",[],504,Neha,Pune

In [37]:
item_df = combined_df.explode("items")
item_df.head()

,order_id,order_date,customer,items,customer_id,name,city
0,1001,2026-10-01,"{'customer_id': 501, 'name': 'Rahul', 'city': ...","{'product_id': 'P101', 'product_name': 'Laptop...",501,Rahul,Pune
0,1001,2026-10-01,"{'customer_id': 501, 'name': 'Rahul', 'city': ...","{'product_id': 'P102', 'product_name': 'Mouse'...",501,Rahul,Pune
1,1002,2026-10-02,"{'customer_id': 502, 'name': 'Priya', 'city': ...","{'product_id': 'P103', 'product_name': 'Keyboa...",502,Priya,Mumbai
2,1003,2026-10-02,"{'customer_id': 503, 'name': 'Amit', 'city': '...","{'product_id': 'P104', 'product_name': 'Phone'...",503,Amit,Delhi
2,1003,2026-10-02,"{'customer_id': 503, 'name': 'Amit', 'city': '...","{'product_id': 'P105', 'product_name': 'Case',...",503,Amit,Delhi

In [38]:
item_df.shape

(7, 7)

In [39]:
item_df[["order_id","items"]]

   order_id                                              items
0      1001  {'product_id': 'P101', 'product_name': 'Laptop...
0      1001  {'product_id': 'P102', 'product_name': 'Mouse'...
1      1002  {'product_id': 'P103', 'product_name': 'Keyboa...
2      1003  {'product_id': 'P104', 'product_name': 'Phone'...
2      1003  {'product_id': 'P105', 'product_name': 'Case',...
2      1003  {'product_id': 'P106', 'product_name': 'Charge...
3      1004                                                NaN

In [40]:
item_df = item_df.dropna(subset= ["items"])

In [42]:
item_df

,order_id,order_date,customer,items,customer_id,name,city
0,1001,2026-10-01,"{'customer_id': 501, 'name': 'Rahul', 'city': ...","{'product_id': 'P101', 'product_name': 'Laptop...",501,Rahul,Pune
0,1001,2026-10-01,"{'customer_id': 501, 'name': 'Rahul', 'city': ...","{'product_id': 'P102', 'product_name': 'Mouse'...",501,Rahul,Pune
1,1002,2026-10-02,"{'customer_id': 502, 'name': 'Priya', 'city': ...","{'product_id': 'P103', 'product_name': 'Keyboa...",502,Priya,Mumbai
2,1003,2026-10-02,"{'customer_id': 503, 'name': 'Amit', 'city': '...","{'product_id': 'P104', 'product_name': 'Phone'...",503,Amit,Delhi
2,1003,2026-10-02,"{'customer_id': 503, 'name': 'Amit', 'city': '...","{'product_id': 'P105', 'product_name': 'Case',...",503,Amit,Delhi
2,1003,2026-10-02,"{'customer_id': 503, 'name': 'Amit', 'city': '...","{'product_id': 'P106', 'product_name': 'Charge...",503,Amit,Delhi

In [44]:
items_df = pd.json_normalize(item_df["items"])

In [45]:
items_df

  product_id product_name  quantity  price
0       P101       Laptop         1  55000
0       P102        Mouse         2    800
1       P103     Keyboard         1   2500
2       P104        Phone         1  30000
2       P105         Case         1   1000
2       P106      Charger         2   1500

In [46]:
item_df.index

Index([0, 0, 1, 2, 2, 2], dtype='int64')

In [47]:
items_df.index

Index([0, 0, 1, 2, 2, 2], dtype='int64')

In [48]:
item_df.reset_index(drop= True)

,order_id,order_date,customer,items,customer_id,name,city
0,1001,2026-10-01,"{'customer_id': 501, 'name': 'Rahul', 'city': ...","{'product_id': 'P101', 'product_name': 'Laptop...",501,Rahul,Pune
1,1001,2026-10-01,"{'customer_id': 501, 'name': 'Rahul', 'city': ...","{'product_id': 'P102', 'product_name': 'Mouse'...",501,Rahul,Pune
2,1002,2026-10-02,"{'customer_id': 502, 'name': 'Priya', 'city': ...","{'product_id': 'P103', 'product_name': 'Keyboa...",502,Priya,Mumbai
3,1003,2026-10-02,"{'customer_id': 503, 'name': 'Amit', 'city': '...","{'product_id': 'P104', 'product_name': 'Phone'...",503,Amit,Delhi
4,1003,2026-10-02,"{'customer_id': 503, 'name': 'Amit', 'city': '...","{'product_id': 'P105', 'product_name': 'Case',...",503,Amit,Delhi
5,1003,2026-10-02,"{'customer_id': 503, 'name': 'Amit', 'city': '...","{'product_id': 'P106', 'product_name': 'Charge...",503,Amit,Delhi

In [49]:
items_df.reset_index(drop= True)

  product_id product_name  quantity  price
0       P101       Laptop         1  55000
1       P102        Mouse         2    800
2       P103     Keyboard         1   2500
3       P104        Phone         1  30000
4       P105         Case         1   1000
5       P106      Charger         2   1500

In [50]:
final_df = pd.concat([item_df,items_df],axis = 1)
final_df

,order_id,order_date,customer,items,customer_id,name,city,product_id,product_name,quantity,price
0,1001,2026-10-01,"{'customer_id': 501, 'name': 'Rahul', 'city': ...","{'product_id': 'P101', 'product_name': 'Laptop...",501,Rahul,Pune,P101,Laptop,1,55000
0,1001,2026-10-01,"{'customer_id': 501, 'name': 'Rahul', 'city': ...","{'product_id': 'P102', 'product_name': 'Mouse'...",501,Rahul,Pune,P102,Mouse,2,800
1,1002,2026-10-02,"{'customer_id': 502, 'name': 'Priya', 'city': ...","{'product_id': 'P103', 'product_name': 'Keyboa...",502,Priya,Mumbai,P103,Keyboard,1,2500
2,1003,2026-10-02,"{'customer_id': 503, 'name': 'Amit', 'city': '...","{'product_id': 'P104', 'product_name': 'Phone'...",503,Amit,Delhi,P104,Phone,1,30000
2,1003,2026-10-02,"{'customer_id': 503, 'name': 'Amit', 'city': '...","{'product_id': 'P105', 'product_name': 'Case',...",503,Amit,Delhi,P105,Case,1,1000
2,1003,2026-10-02,"{'customer_id': 503, 'name': 'Amit', 'city': '...","{'product_id': 'P106', 'product_name': 'Charge...",503,Amit,Delhi,P106,Charger,2,1500

In [54]:
final_df = final_df.drop(columns= ["customer","items"])

In [55]:
final_df = final_df.assign(
    item_revenue = final_df["quantity"] * final_df["price"]
)

In [56]:
final_df

,order_id,order_date,customer_id,name,city,product_id,product_name,quantity,price,item_revenue
0,1001,2026-10-01,501,Rahul,Pune,P101,Laptop,1,55000,55000
0,1001,2026-10-01,501,Rahul,Pune,P102,Mouse,2,800,1600
1,1002,2026-10-02,502,Priya,Mumbai,P103,Keyboard,1,2500,2500
2,1003,2026-10-02,503,Amit,Delhi,P104,Phone,1,30000,30000
2,1003,2026-10-02,503,Amit,Delhi,P105,Case,1,1000,1000
2,1003,2026-10-02,503,Amit,Delhi,P106,Charger,2,1500,3000

In [57]:
item_total_revenue = final_df.groupby("order_id")["item_revenue"].sum()

In [58]:
item_total_revenue

order_id
1001    56600
1002     2500
1003    34000
Name: item_revenue, dtype: int64

In [60]:
item_revenue_per_city = final_df.groupby("city")["item_revenue"].sum()

In [61]:
item_revenue_per_city

city
Delhi     34000
Mumbai     2500
Pune      56600
Name: item_revenue, dtype: int64

In [62]:
product_total_revenue = final_df.groupby("product_name")["item_revenue"].sum()

In [63]:
highest_product_revenue = product_total_revenue.nlargest(1)

In [64]:
highest_product_revenue

product_name
Laptop    55000
Name: item_revenue, dtype: int64