In [4]:
import pandas as pd 

df = pd.read_csv("customer_cdc.csv")
df.head()

   event_id customer_id   name       city    status           updated_at
0      1001        C101   Amit       Pune    ACTIVE  2026-09-20 10:00:00
1      1002        C102   Neha     Mumbai    ACTIVE  2026-09-20 11:30:00
2      1003        C101   Amit  Bangalore    ACTIVE  2026-09-21 09:00:00
3      1004        C103  Rahul      Delhi    ACTIVE  2026-09-21 12:00:00
4      1005        C102   Neha     Mumbai  INACTIVE  2026-09-22 08:30:00

In [6]:
df["updated_at"] = pd.to_datetime(df["updated_at"],errors= "coerce")
df.dtypes

event_id                int64
customer_id            object
name                   object
city                   object
status                 object
updated_at     datetime64[ns]
dtype: object

In [7]:
df.head()

   event_id customer_id   name       city    status          updated_at
0      1001        C101   Amit       Pune    ACTIVE 2026-09-20 10:00:00
1      1002        C102   Neha     Mumbai    ACTIVE 2026-09-20 11:30:00
2      1003        C101   Amit  Bangalore    ACTIVE 2026-09-21 09:00:00
3      1004        C103  Rahul      Delhi    ACTIVE 2026-09-21 12:00:00
4      1005        C102   Neha     Mumbai  INACTIVE 2026-09-22 08:30:00

In [8]:
df

    event_id customer_id   name       city    status          updated_at
0       1001        C101   Amit       Pune    ACTIVE 2026-09-20 10:00:00
1       1002        C102   Neha     Mumbai    ACTIVE 2026-09-20 11:30:00
2       1003        C101   Amit  Bangalore    ACTIVE 2026-09-21 09:00:00
3       1004        C103  Rahul      Delhi    ACTIVE 2026-09-21 12:00:00
4       1005        C102   Neha     Mumbai  INACTIVE 2026-09-22 08:30:00
5       1006        C101   Amit  Hyderabad    ACTIVE 2026-09-22 14:00:00
6       1007        C103  Rahul      Delhi  INACTIVE 2026-09-22 15:00:00
7       1008        C104  Priya    Chennai    ACTIVE                 NaT
8       1009        C104  Priya    Chennai    ACTIVE 2026-09-22 16:00:00
9       1010        C102   Neha       Pune    ACTIVE 2026-09-22 08:30:00
10      1011        C105  Karan     Jaipur    ACTIVE 2026-09-23 10:00:00
11      1012        C105  Karan     Mumbai    ACTIVE 2026-09-23 10:00:00

In [11]:
df[df["updated_at"].isna()]

   event_id customer_id   name     city  status updated_at
7      1008        C104  Priya  Chennai  ACTIVE        NaT