In [1]:
import pandas as pd 

df = pd.read_csv("regional_sales.csv")
df.head()

  sale_id region product month  revenue
0    S001  North  Laptop   Jan    50000
1    S002  North   Phone   Jan    20000
2    S003  South  Laptop   Jan    40000
3    S004  South   Phone   Jan    30000
4    S005  North  Laptop   Feb    30000

In [3]:
df.shape

(13, 5)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   sale_id  13 non-null     object
 1   region   13 non-null     object
 2   product  13 non-null     object
 3   month    13 non-null     object
 4   revenue  13 non-null     int64
dtypes: int64(1), object(4)
memory usage: 648.0+ bytes

In [9]:
pivot_report = df.pivot_table(
    index = "region",
    columns= "product",
    values="revenue",
    aggfunc= "sum"
)
pivot_report.head()

product  Laptop  Phone
region
North     90000  45000
South     85000  65000
West     110000  85000

In [13]:
month_report = df.pivot_table(
    index = "region",
    columns= "month",
    values = "revenue",
    aggfunc= "sum"
)
month_report

month     Feb     Jan
region
North   55000   80000
South   80000   70000
West    95000  100000

In [14]:
df

   sale_id region product month  revenue
0     S001  North  Laptop   Jan    50000
1     S002  North   Phone   Jan    20000
2     S003  South  Laptop   Jan    40000
3     S004  South   Phone   Jan    30000
4     S005  North  Laptop   Feb    30000
5     S006  North   Phone   Feb    25000
6     S007  South  Laptop   Feb    45000
7     S008  South   Phone   Feb    35000
8     S009   West  Laptop   Jan    60000
9     S010   West   Phone   Jan    40000
10    S011   West  Laptop   Feb    50000
11    S012   West   Phone   Feb    45000
12    S013  North  Laptop   Jan    10000

In [17]:

month_report = month_report.reset_index()
long_month_report = month_report.melt(
    id_vars = "region",
    value_vars = ["Jan","Feb"],
    var_name = "month",
    value_name = "total_revenue"
)
long_month_report

  region month  total_revenue
0  North   Jan          80000
1  South   Jan          70000
2   West   Jan         100000
3  North   Feb          55000
4  South   Feb          80000
5   West   Feb          95000

In [18]:
month_report = month_report.reset_index()
long_month_report = month_report.melt(
    id_vars = "region",
    value_vars = ["Jan","Feb"],
    var_name = "month",
    value_name = "total_revenue"
)
long_month_report

  region month  total_revenue
0  North   Jan          80000
1  South   Jan          70000
2   West   Jan         100000
3  North   Feb          55000
4  South   Feb          80000
5   West   Feb          95000

In [22]:
unstacked_df = df.groupby(["region","product"])["revenue"].sum().unstack()
unstacked_df

product  Laptop  Phone
region
North     90000  45000
South     85000  65000
West     110000  85000

In [23]:
df

   sale_id region product month  revenue
0     S001  North  Laptop   Jan    50000
1     S002  North   Phone   Jan    20000
2     S003  South  Laptop   Jan    40000
3     S004  South   Phone   Jan    30000
4     S005  North  Laptop   Feb    30000
5     S006  North   Phone   Feb    25000
6     S007  South  Laptop   Feb    45000
7     S008  South   Phone   Feb    35000
8     S009   West  Laptop   Jan    60000
9     S010   West   Phone   Jan    40000
10    S011   West  Laptop   Feb    50000
11    S012   West   Phone   Feb    45000
12    S013  North  Laptop   Jan    10000

In [32]:
highest_revenue = df.groupby("region")["revenue"].sum().nlargest(1)
highest_revenue

region
West    195000
Name: revenue, dtype: int64