In [1]:
import pandas as pd

data = {
    "customer_id": ["C101","C101","C101","C102","C102","C102"],
    "month": ["Jan","Feb","Mar","Jan","Feb","Mar"],
    "revenue": [1000,1200,1500,2000,1800,2200]
}

df = pd.DataFrame(data)

In [2]:
df

  customer_id month  revenue
0        C101   Jan     1000
1        C101   Feb     1200
2        C101   Mar     1500
3        C102   Jan     2000
4        C102   Feb     1800
5        C102   Mar     2200

In [14]:
df["previous_revenue"] = df.groupby("customer_id")["revenue"].shift(1)
df

,customer_id,month,revenue,previous_revenue,revenue_change,revenue_pct_change,cumulative_revenue,month_sequence
0,C101,Jan,1000,NaN,NaN,NaN,1000,1
1,C101,Feb,1200,1000.0,200.0,20.000000,2200,2
2,C101,Mar,1500,1200.0,300.0,25.000000,3700,3
3,C102,Jan,2000,NaN,NaN,33.333333,2000,1
4,C102,Feb,1800,2000.0,-200.0,-10.000000,3800,2
5,C102,Mar,2200,1800.0,400.0,22.222222,6000,3

In [15]:
df["revenue_change"] = df.groupby("customer_id")["revenue"].diff()
df

,customer_id,month,revenue,previous_revenue,revenue_change,revenue_pct_change,cumulative_revenue,month_sequence
0,C101,Jan,1000,NaN,NaN,NaN,1000,1
1,C101,Feb,1200,1000.0,200.0,20.000000,2200,2
2,C101,Mar,1500,1200.0,300.0,25.000000,3700,3
3,C102,Jan,2000,NaN,NaN,33.333333,2000,1
4,C102,Feb,1800,2000.0,-200.0,-10.000000,3800,2
5,C102,Mar,2200,1800.0,400.0,22.222222,6000,3

In [16]:
df =df.drop(columns= "difference")
df

KeyError: "['difference'] not found in axis"

In [17]:
df["revenue_pct_change"] = df.groupby("customer_id")["revenue"].pct_change() * 100 
df

,customer_id,month,revenue,previous_revenue,revenue_change,revenue_pct_change,cumulative_revenue,month_sequence
0,C101,Jan,1000,NaN,NaN,NaN,1000,1
1,C101,Feb,1200,1000.0,200.0,20.000000,2200,2
2,C101,Mar,1500,1200.0,300.0,25.000000,3700,3
3,C102,Jan,2000,NaN,NaN,NaN,2000,1
4,C102,Feb,1800,2000.0,-200.0,-10.000000,3800,2
5,C102,Mar,2200,1800.0,400.0,22.222222,6000,3

In [11]:
df["cumulative_revenue"] = df.groupby("customer_id")["revenue"].cumsum()
df

,customer_id,month,revenue,previous_revenue,revenue_change,revenue_pct_change,cumulative_revenue
0,C101,Jan,1000,NaN,NaN,NaN,1000
1,C101,Feb,1200,1000.0,200.0,20.000000,2200
2,C101,Mar,1500,1200.0,300.0,25.000000,3700
3,C102,Jan,2000,1500.0,NaN,33.333333,2000
4,C102,Feb,1800,2000.0,-200.0,-10.000000,3800
5,C102,Mar,2200,1800.0,400.0,22.222222,6000

In [13]:
df["month_sequence"] = df.groupby("customer_id").cumcount() + 1
df

,customer_id,month,revenue,previous_revenue,revenue_change,revenue_pct_change,cumulative_revenue,month_sequence
0,C101,Jan,1000,NaN,NaN,NaN,1000,1
1,C101,Feb,1200,1000.0,200.0,20.000000,2200,2
2,C101,Mar,1500,1200.0,300.0,25.000000,3700,3
3,C102,Jan,2000,1500.0,NaN,33.333333,2000,1
4,C102,Feb,1800,2000.0,-200.0,-10.000000,3800,2
5,C102,Mar,2200,1800.0,400.0,22.222222,6000,3