In [1]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "transaction_id": [1001, 1002, 1003, 1004, 1005],
    "amount": [2500, 18000, 75000, 1200, 45000],
    "country": ["India", "USA", "India", "UK", "Germany"]
})

df

   transaction_id  amount  country
0            1001    2500    India
1            1002   18000      USA
2            1003   75000    India
3            1004    1200       UK
4            1005   45000  Germany

In [2]:
df["transaction_fees"] = df["amount"] * 1.5/100
df

   transaction_id  amount  country  transaction_fees
0            1001    2500    India              37.5
1            1002   18000      USA             270.0
2            1003   75000    India            1125.0
3            1004    1200       UK              18.0
4            1005   45000  Germany             675.0

In [7]:
df["category"] = np.where(df["amount"] >= 40000,"HIGH","NORMAL")
df

,transaction_id,amount,country,transaction_fees,category,international_flag,high_international_flag
0,1001,2500,India,37.5,NORMAL,YES,OK
1,1002,18000,USA,270.0,NORMAL,NO,OK
2,1003,75000,India,1125.0,HIGH,YES,OK
3,1004,1200,UK,18.0,NORMAL,NO,OK
4,1005,45000,Germany,675.0,HIGH,NO,REVIEW

In [8]:
df["international_flag"] = np.where(df["country"] != "India","YES","NO")
df

,transaction_id,amount,country,transaction_fees,category,international_flag,high_international_flag
0,1001,2500,India,37.5,NORMAL,NO,OK
1,1002,18000,USA,270.0,NORMAL,YES,OK
2,1003,75000,India,1125.0,HIGH,NO,OK
3,1004,1200,UK,18.0,NORMAL,YES,OK
4,1005,45000,Germany,675.0,HIGH,YES,REVIEW

In [9]:
df["high_international_flag"] = np.where((df["amount"] >= 40000) & (df["country"] != "India"),"REVIEW","OK")
df

,transaction_id,amount,country,transaction_fees,category,international_flag,high_international_flag
0,1001,2500,India,37.5,NORMAL,NO,OK
1,1002,18000,USA,270.0,NORMAL,YES,OK
2,1003,75000,India,1125.0,HIGH,NO,OK
3,1004,1200,UK,18.0,NORMAL,YES,OK
4,1005,45000,Germany,675.0,HIGH,YES,REVIEW