In [1]:
import pandas as pd
import numpy as np 

df = pd.DataFrame({
    "transaction_id": [2001, 2002, 2003, 2004, 2005, 2006],
    "amount": [5000, 65000, 25000, 90000, 15000, 55000],
    "country": ["India", "USA", "UK", "Russia", "India", "Germany"],
    "channel": ["UPI", "CARD", "CARD", "WIRE", "UPI", "WIRE"]
})

In [2]:
df.head()

   transaction_id  amount country channel
0            2001    5000   India     UPI
1            2002   65000     USA    CARD
2            2003   25000      UK    CARD
3            2004   90000  Russia    WIRE
4            2005   15000   India     UPI

In [3]:
country_risk = {
    "India": "LOW",
    "USA": "MEDIUM",
    "UK": "MEDIUM",
    "Russia": "HIGH",
    "Germany": "LOW"
}

df["country_risk"] = df["country"].map(country_risk)
df

   transaction_id  amount  country channel country_risk
0            2001    5000    India     UPI          LOW
1            2002   65000      USA    CARD       MEDIUM
2            2003   25000       UK    CARD       MEDIUM
3            2004   90000   Russia    WIRE         HIGH
4            2005   15000    India     UPI          LOW
5            2006   55000  Germany    WIRE          LOW

In [5]:
df["high_value_flag"] = np.where(df["amount"] >= 50000,"YES","NO")
df

   transaction_id  amount  country channel country_risk high_value_flag
0            2001    5000    India     UPI          LOW              NO
1            2002   65000      USA    CARD       MEDIUM             YES
2            2003   25000       UK    CARD       MEDIUM              NO
3            2004   90000   Russia    WIRE         HIGH             YES
4            2005   15000    India     UPI          LOW              NO
5            2006   55000  Germany    WIRE          LOW             YES

In [6]:
df = df.assign(
    processing_fee = df["amount"] * 0.02
)
df

,transaction_id,amount,country,channel,country_risk,high_value_flag,processing_fee
0,2001,5000,India,UPI,LOW,NO,100.0
1,2002,65000,USA,CARD,MEDIUM,YES,1300.0
2,2003,25000,UK,CARD,MEDIUM,NO,500.0
3,2004,90000,Russia,WIRE,HIGH,YES,1800.0
4,2005,15000,India,UPI,LOW,NO,300.0
5,2006,55000,Germany,WIRE,LOW,YES,1100.0

In [7]:
def risk_rule(row):
    if row["amount"] >= 50000 and row["country_risk"] == "HIGH":
        return "HIGH"
    elif row["amount"] >= 50000 or row["channel"] == "WIRE":
        return "MEDIUM"
    else:
        return "LOW"

df["risk_level"] = df.apply(risk_rule, axis = 1)
df

,transaction_id,amount,country,channel,country_risk,high_value_flag,processing_fee,risk_level
0,2001,5000,India,UPI,LOW,NO,100.0,LOW
1,2002,65000,USA,CARD,MEDIUM,YES,1300.0,MEDIUM
2,2003,25000,UK,CARD,MEDIUM,NO,500.0,LOW
3,2004,90000,Russia,WIRE,HIGH,YES,1800.0,HIGH
4,2005,15000,India,UPI,LOW,NO,300.0,LOW
5,2006,55000,Germany,WIRE,LOW,YES,1100.0,MEDIUM