In [2]:
import pandas as pd
import numpy as np 

country_risk = {
    "India": "LOW",
    "USA": "MEDIUM",
    "UK": "MEDIUM",
    "Russia": "HIGH",
    "Germany": "LOW"
}

In [3]:
df = pd.read_csv("fraud_transactions.csv")
df.head()

  transaction_id customer_id  amount country channel   status
0         TX1001        C101    4500   India     UPI  SUCCESS
1         TX1002        C102   72000     USA    CARD  SUCCESS
2         TX1003        C103   95000  Russia    WIRE  SUCCESS
3         TX1004        C104   18000      UK    CARD  SUCCESS
4         TX1005        C105   55000   India     UPI  SUCCESS

In [4]:
df["country_risk"] = df["country"].map(country_risk)
df

  transaction_id customer_id  amount  country channel   status country_risk
0         TX1001        C101    4500    India     UPI  SUCCESS          LOW
1         TX1002        C102   72000      USA    CARD  SUCCESS       MEDIUM
2         TX1003        C103   95000   Russia    WIRE  SUCCESS         HIGH
3         TX1004        C104   18000       UK    CARD  SUCCESS       MEDIUM
4         TX1005        C105   55000    India     UPI  SUCCESS          LOW
5         TX1006        C106  120000  Germany    WIRE  SUCCESS          LOW
6         TX1007        C107   80000   Russia    CARD   FAILED         HIGH
7         TX1008        C108   35000      USA    WIRE  SUCCESS       MEDIUM
8         TX1009        C109   15000    India    CARD  SUCCESS          LOW
9         TX1010        C110   65000   France    CARD  SUCCESS          NaN

In [5]:
df["high_value_flag"] = np.where(df["amount"] >= 50000,"YES","NO")
df

,transaction_id,customer_id,amount,country,channel,status,country_risk,high_value_flag
0,TX1001,C101,4500,India,UPI,SUCCESS,LOW,NO
1,TX1002,C102,72000,USA,CARD,SUCCESS,MEDIUM,YES
2,TX1003,C103,95000,Russia,WIRE,SUCCESS,HIGH,YES
3,TX1004,C104,18000,UK,CARD,SUCCESS,MEDIUM,NO
4,TX1005,C105,55000,India,UPI,SUCCESS,LOW,YES
5,TX1006,C106,120000,Germany,WIRE,SUCCESS,LOW,YES
6,TX1007,C107,80000,Russia,CARD,FAILED,HIGH,YES
7,TX1008,C108,35000,USA,WIRE,SUCCESS,MEDIUM,NO
8,TX1009,C109,15000,India,CARD,SUCCESS,LOW,NO
9,TX1010,C110,65000,France,CARD,SUCCESS,NaN,YES

In [6]:
df["transaction_fee"] = df["amount"] * 1.5 / 100
df

,transaction_id,customer_id,amount,country,channel,status,country_risk,high_value_flag,transaction_fee
0,TX1001,C101,4500,India,UPI,SUCCESS,LOW,NO,67.5
1,TX1002,C102,72000,USA,CARD,SUCCESS,MEDIUM,YES,1080.0
2,TX1003,C103,95000,Russia,WIRE,SUCCESS,HIGH,YES,1425.0
3,TX1004,C104,18000,UK,CARD,SUCCESS,MEDIUM,NO,270.0
4,TX1005,C105,55000,India,UPI,SUCCESS,LOW,YES,825.0
5,TX1006,C106,120000,Germany,WIRE,SUCCESS,LOW,YES,1800.0
6,TX1007,C107,80000,Russia,CARD,FAILED,HIGH,YES,1200.0
7,TX1008,C108,35000,USA,WIRE,SUCCESS,MEDIUM,NO,525.0
8,TX1009,C109,15000,India,CARD,SUCCESS,LOW,NO,225.0
9,TX1010,C110,65000,France,CARD,SUCCESS,NaN,YES,975.0

In [10]:
def risk_level(row):
    if row["amount"] >= 75000 and row["country_risk"] == "HIGH" and row["status"] == "SUCCESS":
        return "HIGH"
    elif row["amount"] >= 50000 or row["channel"] == "WIRE":
        return "MEDIUM"
    else:
        return "LOW"

df["risk_level"] = df.apply(risk_level,axis= 1)
df

,transaction_id,customer_id,amount,country,channel,status,country_risk,high_value_flag,transaction_fee,row_level,risk_level
0,TX1001,C101,4500,India,UPI,SUCCESS,LOW,NO,67.5,LOW,LOW
1,TX1002,C102,72000,USA,CARD,SUCCESS,MEDIUM,YES,1080.0,MEDIUM,MEDIUM
2,TX1003,C103,95000,Russia,WIRE,SUCCESS,HIGH,YES,1425.0,HIGH,HIGH
3,TX1004,C104,18000,UK,CARD,SUCCESS,MEDIUM,NO,270.0,LOW,LOW
4,TX1005,C105,55000,India,UPI,SUCCESS,LOW,YES,825.0,MEDIUM,MEDIUM
5,TX1006,C106,120000,Germany,WIRE,SUCCESS,LOW,YES,1800.0,MEDIUM,MEDIUM
6,TX1007,C107,80000,Russia,CARD,FAILED,HIGH,YES,1200.0,MEDIUM,MEDIUM
7,TX1008,C108,35000,USA,WIRE,SUCCESS,MEDIUM,NO,525.0,MEDIUM,MEDIUM
8,TX1009,C109,15000,India,CARD,SUCCESS,LOW,NO,225.0,LOW,LOW
9,TX1010,C110,65000,France,CARD,SUCCESS,NaN,YES,975.0,MEDIUM,MEDIUM

In [11]:
df["manual_review"] = np.where(df["risk_level"] == "HIGH","YES","NO")
df

,transaction_id,customer_id,amount,country,channel,status,country_risk,high_value_flag,transaction_fee,row_level,risk_level,manual_review
0,TX1001,C101,4500,India,UPI,SUCCESS,LOW,NO,67.5,LOW,LOW,NO
1,TX1002,C102,72000,USA,CARD,SUCCESS,MEDIUM,YES,1080.0,MEDIUM,MEDIUM,NO
2,TX1003,C103,95000,Russia,WIRE,SUCCESS,HIGH,YES,1425.0,HIGH,HIGH,YES
3,TX1004,C104,18000,UK,CARD,SUCCESS,MEDIUM,NO,270.0,LOW,LOW,NO
4,TX1005,C105,55000,India,UPI,SUCCESS,LOW,YES,825.0,MEDIUM,MEDIUM,NO
5,TX1006,C106,120000,Germany,WIRE,SUCCESS,LOW,YES,1800.0,MEDIUM,MEDIUM,NO
6,TX1007,C107,80000,Russia,CARD,FAILED,HIGH,YES,1200.0,MEDIUM,MEDIUM,NO
7,TX1008,C108,35000,USA,WIRE,SUCCESS,MEDIUM,NO,525.0,MEDIUM,MEDIUM,NO
8,TX1009,C109,15000,India,CARD,SUCCESS,LOW,NO,225.0,LOW,LOW,NO
9,TX1010,C110,65000,France,CARD,SUCCESS,NaN,YES,975.0,MEDIUM,MEDIUM,NO

In [14]:
df = df[["transaction_id","customer_id","amount","country","country_risk","risk_level","manual_review"]]

In [13]:
df

,transaction_id,customer_id,amount,country,country_risk,risk_level,manual_review
0,TX1001,C101,4500,India,LOW,LOW,NO
1,TX1002,C102,72000,USA,MEDIUM,MEDIUM,NO
2,TX1003,C103,95000,Russia,HIGH,HIGH,YES
3,TX1004,C104,18000,UK,MEDIUM,LOW,NO
4,TX1005,C105,55000,India,LOW,MEDIUM,NO
5,TX1006,C106,120000,Germany,LOW,MEDIUM,NO
6,TX1007,C107,80000,Russia,HIGH,MEDIUM,NO
7,TX1008,C108,35000,USA,MEDIUM,MEDIUM,NO
8,TX1009,C109,15000,India,LOW,LOW,NO
9,TX1010,C110,65000,France,NaN,MEDIUM,NO

In [15]:
df.groupby("risk_level")["transaction_id"].count()

risk_level
HIGH      1
LOW       3
MEDIUM    6
Name: transaction_id, dtype: int64

In [18]:
fraud_records = df[df["country_risk"].isna()]
fraud_records

,transaction_id,customer_id,amount,country,country_risk,risk_level,manual_review
9,TX1010,C110,65000,France,NaN,MEDIUM,NO