In [36]:
import pandas as pd 

target_df = pd.DataFrame(
    {
        "customer_id":["101","102"],
        "city":["Pune","Mumbai"],
        "updated_at" : ["2026-09-20","2026-09-21"]
    }
)

batch_df = pd.DataFrame(
    {
        "customer_id" : ["102","103"],
        "city":["Delhi","Mumbai"],
        "updated_at":["2026-09-29","2026-09-29"]
    }
)

In [37]:
target_df.dtypes

customer_id    object
city           object
updated_at     object
dtype: object

In [38]:
target_df["updated_at"] = pd.to_datetime(target_df["updated_at"],errors = "coerce")

In [39]:
batch_df["updated_at"] = pd.to_datetime(batch_df["updated_at"],errors = "coerce")

In [40]:
combined_df = pd.concat([target_df,batch_df],ignore_index = True)
combined_df

  customer_id    city updated_at
0         101    Pune 2026-09-20
1         102  Mumbai 2026-09-21
2         102   Delhi 2026-09-29
3         103  Mumbai 2026-09-29

In [41]:
combined_df = combined_df.sort_values(by=["customer_id","updated_at"],ascending=[True,False])

In [42]:
combined_df

  customer_id    city updated_at
0         101    Pune 2026-09-20
2         102   Delhi 2026-09-29
1         102  Mumbai 2026-09-21
3         103  Mumbai 2026-09-29

In [43]:
combined_df.dtypes

customer_id            object
city                   object
updated_at     datetime64[ns]
dtype: object

In [44]:
combined_df["customer_id"].tolist()

['101', '102', '102', '103']

In [45]:
combined_df = combined_df.drop_duplicates(subset = ["customer_id"],keep = "first")
combined_df

  customer_id    city updated_at
0         101    Pune 2026-09-20
2         102   Delhi 2026-09-29
3         103  Mumbai 2026-09-29