In [1]:
import pandas as pd

target_df = pd.DataFrame(
    {
        "customer_id":[101,102,103],
        "name" : ["Amit","Neha","Raj"]
    }
)

batch_df = pd.DataFrame(
    {
        "customer_id":[103,104,105],
        "name":["Raj","Priya","Sam"]
    }
)

In [3]:
target_df

   customer_id  name
0          101  Amit
1          102  Neha
2          103   Raj

In [4]:
batch_df

   customer_id   name
0          103    Raj
1          104  Priya
2          105    Sam

In [ ]:
new_df = batch_df.merge(target_df,on = "customer_id",how = "left",indicator= True)
new_df

   customer_id name_x name_y     _merge
0          103    Raj    Raj       both
1          104  Priya    NaN  left_only
2          105    Sam    NaN  left_only

In [6]:
new_df = new_df[new_df["_merge"] == "left_only"]

In [7]:
new_df

   customer_id name_x name_y     _merge
1          104  Priya    NaN  left_only
2          105    Sam    NaN  left_only