In [1]:
import pandas as pd 

target_df =pd.read_csv("customer_target.csv")
batch_df = pd.read_csv("customer_batch.csv")

In [2]:
target_df.dtypes

customer_id    object
name           object
city           object
email          object
updated_at     object
event_id        int64
dtype: object

In [3]:
batch_df.dtypes

customer_id    object
name           object
city           object
email          object
updated_at     object
event_id        int64
dtype: object

In [4]:
target_df["updated_at"] = pd.to_datetime(target_df["updated_at"],errors = "coerce")
batch_df["updated_at"] = pd.to_datetime(batch_df["updated_at"],errors = "coerce")

In [5]:
target_df.dtypes
batch_df.dtypes

customer_id            object
name                   object
city                   object
email                  object
updated_at     datetime64[ns]
event_id                int64
dtype: object

In [6]:
target_df.dtypes

customer_id            object
name                   object
city                   object
email                  object
updated_at     datetime64[ns]
event_id                int64
dtype: object

In [8]:
target_df

  customer_id   name     city            email          updated_at  event_id
0        C101   Amit     Pune   amit@email.com 2026-09-20 10:00:00      1001
1        C102   Neha   Mumbai   neha@email.com 2026-09-21 11:00:00      1002
2        C103    Raj    Delhi    raj@email.com 2026-09-22 09:30:00      1003
3        C104  Priya  Chennai  priya@email.com 2026-09-23 14:00:00      1004

In [9]:
batch_df

,customer_id,name,city,email,updated_at,event_id
0,C102,Neha,Bangalore,neha@email.com,2026-09-29 09:00:00,2001
1,C103,Raj,Delhi,raj.new@email.com,2026-09-29 10:00:00,2002
2,C105,Sam,Hyderabad,sam@email.com,2026-09-29 11:00:00,2003
3,C106,Riya,Pune,riya@email.com,2026-09-29 12:00:00,2004
4,C102,Neha,Bangalore,neha@email.com,2026-09-29 09:00:00,2001
5,C104,Priya,Mumbai,priya@email.com,NaT,2005

In [11]:
batch_df.dropna(subset= ["updated_at"])

,customer_id,name,city,email,updated_at,event_id
0,C102,Neha,Bangalore,neha@email.com,2026-09-29 09:00:00,2001
1,C103,Raj,Delhi,raj.new@email.com,2026-09-29 10:00:00,2002
2,C105,Sam,Hyderabad,sam@email.com,2026-09-29 11:00:00,2003
3,C106,Riya,Pune,riya@email.com,2026-09-29 12:00:00,2004
4,C102,Neha,Bangalore,neha@email.com,2026-09-29 09:00:00,2001

In [12]:
batch_df

,customer_id,name,city,email,updated_at,event_id
0,C102,Neha,Bangalore,neha@email.com,2026-09-29 09:00:00,2001
1,C103,Raj,Delhi,raj.new@email.com,2026-09-29 10:00:00,2002
2,C105,Sam,Hyderabad,sam@email.com,2026-09-29 11:00:00,2003
3,C106,Riya,Pune,riya@email.com,2026-09-29 12:00:00,2004
4,C102,Neha,Bangalore,neha@email.com,2026-09-29 09:00:00,2001
5,C104,Priya,Mumbai,priya@email.com,NaT,2005

In [14]:
batch_df = batch_df.dropna(subset=["updated_at"])

In [15]:
batch_df.head()

,customer_id,name,city,email,updated_at,event_id
0,C102,Neha,Bangalore,neha@email.com,2026-09-29 09:00:00,2001
1,C103,Raj,Delhi,raj.new@email.com,2026-09-29 10:00:00,2002
2,C105,Sam,Hyderabad,sam@email.com,2026-09-29 11:00:00,2003
3,C106,Riya,Pune,riya@email.com,2026-09-29 12:00:00,2004
4,C102,Neha,Bangalore,neha@email.com,2026-09-29 09:00:00,2001

In [19]:
batch_df[batch_df.duplicated()]

  customer_id  name       city           email          updated_at  event_id
4        C102  Neha  Bangalore  neha@email.com 2026-09-29 09:00:00      2001

In [20]:
batch_df = batch_df.drop_duplicates()

In [21]:
batch_df

,customer_id,name,city,email,updated_at,event_id
0,C102,Neha,Bangalore,neha@email.com,2026-09-29 09:00:00,2001
1,C103,Raj,Delhi,raj.new@email.com,2026-09-29 10:00:00,2002
2,C105,Sam,Hyderabad,sam@email.com,2026-09-29 11:00:00,2003
3,C106,Riya,Pune,riya@email.com,2026-09-29 12:00:00,2004

In [27]:
new_df = batch_df.merge(target_df,on="customer_id",how = "left",indicator = True)
new_df = new_df[new_df["_merge"] == "left_only"]

In [28]:
new_df

,customer_id,name_x,city_x,email_x,updated_at_x,event_id_x,name_y,city_y,email_y,updated_at_y,event_id_y,_merge
2,C105,Sam,Hyderabad,sam@email.com,2026-09-29 11:00:00,2003,NaN,NaN,NaN,NaT,NaN,left_only
3,C106,Riya,Pune,riya@email.com,2026-09-29 12:00:00,2004,NaN,NaN,NaN,NaT,NaN,left_only

In [26]:
target_df

  customer_id   name     city            email          updated_at  event_id
0        C101   Amit     Pune   amit@email.com 2026-09-20 10:00:00      1001
1        C102   Neha   Mumbai   neha@email.com 2026-09-21 11:00:00      1002
2        C103    Raj    Delhi    raj@email.com 2026-09-22 09:30:00      1003
3        C104  Priya  Chennai  priya@email.com 2026-09-23 14:00:00      1004

In [30]:
final_df = pd.concat([target_df,new_df],ignore_index= True)

In [31]:
final_df

,customer_id,name,city,email,updated_at,event_id,name_x,city_x,email_x,updated_at_x,event_id_x,name_y,city_y,email_y,updated_at_y,event_id_y,_merge
0,C101,Amit,Pune,amit@email.com,2026-09-20 10:00:00,1001.0,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1,C102,Neha,Mumbai,neha@email.com,2026-09-21 11:00:00,1002.0,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN
2,C103,Raj,Delhi,raj@email.com,2026-09-22 09:30:00,1003.0,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN
3,C104,Priya,Chennai,priya@email.com,2026-09-23 14:00:00,1004.0,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN
4,C105,NaN,NaN,NaN,NaT,NaN,Sam,Hyderabad,sam@email.com,2026-09-29 11:00:00,2003.0,NaN,NaN,NaN,NaT,NaN,left_only
5,C106,NaN,NaN,NaN,NaT,NaN,Riya,Pune,riya@email.com,2026-09-29 12:00:00,2004.0,NaN,NaN,NaN,NaT,NaN,left_only