In [1]:
import pandas as pd 

print(pd.__version__)

3.0.1

In [2]:
 

df = pd.read_csv("logistics_shipments.csv")
print(df)

   shipment_id     warehouse region customer_id shipment_status  revenue  \
0        S1001       WH_PUNE   West        C101       DELIVERED    12500
1        S1002       WH_PUNE   West        C102       DELIVERED     8000
2        S1003     WH_MUMBAI   West        C103      IN_TRANSIT    15000
3        S1004  WH_BANGALORE  South        C101       DELIVERED    11000
4        S1005       WH_PUNE   West        C101       DELIVERED     6500
5        S1006  WH_BANGALORE  South        C104       DELIVERED    18000
6        S1007     WH_MUMBAI   West        C105       DELIVERED     9000
7        S1008      WH_DELHI  North        C106       DELIVERED    20000
8        S1009      WH_DELHI  North        C107      IN_TRANSIT    14000
9        S1010  WH_BANGALORE  South        C108       DELIVERED     7500
10       S1011       WH_PUNE   West        C109       CANCELLED     5000
11       S1012      WH_DELHI  North        C106       DELIVERED    16000

    delivery_days
0               3
1               2
2               4
3               5
4               4
5               3
6               6
7               4
8               2
9               5
10              1
11              3

In [3]:
df.head()

,shipment_id,warehouse,region,customer_id,shipment_status,revenue,delivery_days
0,S1001,WH_PUNE,West,C101,DELIVERED,12500,3
1,S1002,WH_PUNE,West,C102,DELIVERED,8000,2
2,S1003,WH_MUMBAI,West,C103,IN_TRANSIT,15000,4
3,S1004,WH_BANGALORE,South,C101,DELIVERED,11000,5
4,S1005,WH_PUNE,West,C101,DELIVERED,6500,4

In [4]:
df.shape

(12, 7)

In [5]:
df.columns

Index(['shipment_id', 'warehouse', 'region', 'customer_id', 'shipment_status',
       'revenue', 'delivery_days'],
      dtype='str')

In [6]:
df.dtypes

shipment_id          str
warehouse            str
region               str
customer_id          str
shipment_status      str
revenue            int64
delivery_days      int64
dtype: object

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   shipment_id      12 non-null     str
 1   warehouse        12 non-null     str
 2   region           12 non-null     str
 3   customer_id      12 non-null     str
 4   shipment_status  12 non-null     str
 5   revenue          12 non-null     int64
 6   delivery_days    12 non-null     int64
dtypes: int64(2), str(5)
memory usage: 1.2 KB

In [13]:
df.head()

,shipment_id,warehouse,region,customer_id,shipment_status,revenue,delivery_days
0,S1001,WH_PUNE,West,C101,DELIVERED,12500,3
1,S1002,WH_PUNE,West,C102,DELIVERED,8000,2
2,S1003,WH_MUMBAI,West,C103,IN_TRANSIT,15000,4
3,S1004,WH_BANGALORE,South,C101,DELIVERED,11000,5
4,S1005,WH_PUNE,West,C101,DELIVERED,6500,4

In [14]:
delivered_df = df[df["shipment_status"] == "DELIVERED"]
delivered_df.head()

,shipment_id,warehouse,region,customer_id,shipment_status,revenue,delivery_days
0,S1001,WH_PUNE,West,C101,DELIVERED,12500,3
1,S1002,WH_PUNE,West,C102,DELIVERED,8000,2
3,S1004,WH_BANGALORE,South,C101,DELIVERED,11000,5
4,S1005,WH_PUNE,West,C101,DELIVERED,6500,4
5,S1006,WH_BANGALORE,South,C104,DELIVERED,18000,3

In [16]:
warehouse_kpi = delivered_df.groupby("warehouse").agg(
    shipment_count = ("shipment_id","count"),
    total_revenue = ("revenue","sum"),
    average_revenue = ("revenue","mean"),
    average_delivery_days = ("delivery_days","mean"),
    unique_customers = ("customer_id","nunique")
).reset_index()

In [17]:
warehouse_kpi.head()

,warehouse,shipment_count,total_revenue,average_revenue,average_delivery_days,unique_customers
0,WH_BANGALORE,3,36500,12166.666667,4.333333,3
1,WH_DELHI,2,36000,18000.000000,3.500000,1
2,WH_MUMBAI,1,9000,9000.000000,6.000000,1
3,WH_PUNE,3,27000,9000.000000,3.000000,2

In [18]:
warehouse_kpi.nlargest(1,"average_delivery_days")

,warehouse,shipment_count,total_revenue,average_revenue,average_delivery_days,unique_customers
2,WH_MUMBAI,1,9000,9000.0,6.0,1

In [19]:
warehouse_kpi[warehouse_kpi["total_revenue"] > 20000]

,warehouse,shipment_count,total_revenue,average_revenue,average_delivery_days,unique_customers
0,WH_BANGALORE,3,36500,12166.666667,4.333333,3
1,WH_DELHI,2,36000,18000.000000,3.500000,1
3,WH_PUNE,3,27000,9000.000000,3.000000,2

In [20]:
warehouse_kpi = warehouse_kpi.sort_values("total_revenue", ascending=False)

In [21]:
warehouse_kpi.head()

,warehouse,shipment_count,total_revenue,average_revenue,average_delivery_days,unique_customers
0,WH_BANGALORE,3,36500,12166.666667,4.333333,3
1,WH_DELHI,2,36000,18000.000000,3.500000,1
3,WH_PUNE,3,27000,9000.000000,3.000000,2
2,WH_MUMBAI,1,9000,9000.000000,6.000000,1