In [1]:
import pandas as pd 

df = pd.DataFrame({
    "region":["East","East","East","West","West"],
    "product":["Laptop","Phone","Tablet","Laptop","Phone"],
    "revenue":[900,700,700,1000,600]
}
)

In [2]:
df.head()

  region product  revenue
0   East  Laptop      900
1   East   Phone      700
2   East  Tablet      700
3   West  Laptop     1000
4   West   Phone      600

In [3]:
df["revenue_rank"] = df.groupby("region")["revenue"].rank(method = "dense",ascending  = False)
df.head()

  region product  revenue  revenue_rank
0   East  Laptop      900           1.0
1   East   Phone      700           2.0
2   East  Tablet      700           2.0
3   West  Laptop     1000           1.0
4   West   Phone      600           2.0

In [4]:
df["region_avg_revenue"] = df.groupby("region")["revenue"].transform("mean")
df.head()

  region product  revenue  revenue_rank  region_avg_revenue
0   East  Laptop      900           1.0          766.666667
1   East   Phone      700           2.0          766.666667
2   East  Tablet      700           2.0          766.666667
3   West  Laptop     1000           1.0          800.000000
4   West   Phone      600           2.0          800.000000

In [11]:
df["region_total_revenue"] = df.groupby("region")["revenue"].transform("sum")
df.head()

,region,product,revenue,revenue_rank,region_avg_revenue,region_total_revenue,revenue_contribution_pct
0,East,Laptop,900,1.0,766.666667,2300,NaN
1,East,Phone,700,2.0,766.666667,2300,-0.222222
2,East,Tablet,700,2.0,766.666667,2300,0.000000
3,West,Laptop,1000,1.0,800.000000,1600,NaN
4,West,Phone,600,2.0,800.000000,1600,-0.400000

In [14]:
df.drop(columns= "revenue_contribution_pct")

,region,product,revenue,revenue_rank,region_avg_revenue,region_total_revenue
0,East,Laptop,900,1.0,766.666667,2300
1,East,Phone,700,2.0,766.666667,2300
2,East,Tablet,700,2.0,766.666667,2300
3,West,Laptop,1000,1.0,800.000000,1600
4,West,Phone,600,2.0,800.000000,1600

In [15]:
df["revenue_contribution_pct"] = df["revenue"]/df["region_total_revenue"] * 100
df.head()

,region,product,revenue,revenue_rank,region_avg_revenue,region_total_revenue,revenue_contribution_pct
0,East,Laptop,900,1.0,766.666667,2300,39.130435
1,East,Phone,700,2.0,766.666667,2300,30.434783
2,East,Tablet,700,2.0,766.666667,2300,30.434783
3,West,Laptop,1000,1.0,800.000000,1600,62.500000
4,West,Phone,600,2.0,800.000000,1600,37.500000

In [18]:
df.head()

,region,product,revenue,revenue_rank,region_avg_revenue,region_total_revenue,revenue_contribution_pct
0,East,Laptop,900,1.0,766.666667,2300,39.130435
1,East,Phone,700,2.0,766.666667,2300,30.434783
2,East,Tablet,700,2.0,766.666667,2300,30.434783
3,West,Laptop,1000,1.0,800.000000,1600,62.500000
4,West,Phone,600,2.0,800.000000,1600,37.500000

In [20]:
top_product = df[df["revenue_rank"] == 1.0]
top_product.head()

,region,product,revenue,revenue_rank,region_avg_revenue,region_total_revenue,revenue_contribution_pct
0,East,Laptop,900,1.0,766.666667,2300,39.130435
3,West,Laptop,1000,1.0,800.000000,1600,62.500000