In [14]:
import pandas as pd 
import numpy as np

df= pd.read_csv("product_sales.csv")
df.head()

  region     product     category  revenue
0  North      Laptop  Electronics    85000
1  North       Phone  Electronics    62000
2  North      Tablet  Electronics    62000
3  North  Headphones  Accessories    28000
4  South      Laptop  Electronics    92000

In [15]:
df["revenue_rank"] = df.groupby("region")["revenue"].rank(method = "dense",ascending = False)
df.head()

  region     product     category  revenue  revenue_rank
0  North      Laptop  Electronics    85000           1.0
1  North       Phone  Electronics    62000           2.0
2  North      Tablet  Electronics    62000           2.0
3  North  Headphones  Accessories    28000           3.0
4  South      Laptop  Electronics    92000           1.0

In [16]:
df["region_avg_revenue"] = df.groupby("region")["revenue"].transform("mean")
df.head()

  region     product     category  revenue  revenue_rank  region_avg_revenue
0  North      Laptop  Electronics    85000           1.0             59250.0
1  North       Phone  Electronics    62000           2.0             59250.0
2  North      Tablet  Electronics    62000           2.0             59250.0
3  North  Headphones  Accessories    28000           3.0             59250.0
4  South      Laptop  Electronics    92000           1.0             62500.0

In [17]:
df

   region     product     category  revenue  revenue_rank  region_avg_revenue
0   North      Laptop  Electronics    85000           1.0             59250.0
1   North       Phone  Electronics    62000           2.0             59250.0
2   North      Tablet  Electronics    62000           2.0             59250.0
3   North  Headphones  Accessories    28000           3.0             59250.0
4   South      Laptop  Electronics    92000           1.0             62500.0
5   South       Phone  Electronics    75000           2.0             62500.0
6   South      Tablet  Electronics    48000           3.0             62500.0
7   South  Headphones  Accessories    35000           4.0             62500.0
8    West      Laptop  Electronics    70000           2.0             61250.0
9    West       Phone  Electronics    88000           1.0             61250.0
10   West      Tablet  Electronics    55000           3.0             61250.0
11   West  Headphones  Accessories    32000           4.0             61250.0

In [18]:
df["region_total_revenue"] = df.groupby("region")["revenue"].transform("sum")
df.head()

,region,product,category,revenue,revenue_rank,region_avg_revenue,region_total_revenue
0,North,Laptop,Electronics,85000,1.0,59250.0,237000
1,North,Phone,Electronics,62000,2.0,59250.0,237000
2,North,Tablet,Electronics,62000,2.0,59250.0,237000
3,North,Headphones,Accessories,28000,3.0,59250.0,237000
4,South,Laptop,Electronics,92000,1.0,62500.0,250000

In [19]:
df["revenue_contribution_pct"] = df["revenue"]/ df["region_total_revenue"] * 100
df.head()

,region,product,category,revenue,revenue_rank,region_avg_revenue,region_total_revenue,revenue_contribution_pct
0,North,Laptop,Electronics,85000,1.0,59250.0,237000,35.864979
1,North,Phone,Electronics,62000,2.0,59250.0,237000,26.160338
2,North,Tablet,Electronics,62000,2.0,59250.0,237000,26.160338
3,North,Headphones,Accessories,28000,3.0,59250.0,237000,11.814346
4,South,Laptop,Electronics,92000,1.0,62500.0,250000,36.800000

In [23]:
df["above_region_avg"] = np.where(df["revenue"] > df["region_avg_revenue"],"YES","NO")
df.head()

,region,product,category,revenue,revenue_rank,region_avg_revenue,region_total_revenue,revenue_contribution_pct,above_region_avg
0,North,Laptop,Electronics,85000,1.0,59250.0,237000,35.864979,YES
1,North,Phone,Electronics,62000,2.0,59250.0,237000,26.160338,YES
2,North,Tablet,Electronics,62000,2.0,59250.0,237000,26.160338,YES
3,North,Headphones,Accessories,28000,3.0,59250.0,237000,11.814346,NO
4,South,Laptop,Electronics,92000,1.0,62500.0,250000,36.800000,YES

In [30]:
top_2_products = df[df["revenue_rank"] <= 2]
top_2_products

,region,product,category,revenue,revenue_rank,region_avg_revenue,region_total_revenue,revenue_contribution_pct,above_region_avg
0,North,Laptop,Electronics,85000,1.0,59250.0,237000,35.864979,YES
1,North,Phone,Electronics,62000,2.0,59250.0,237000,26.160338,YES
2,North,Tablet,Electronics,62000,2.0,59250.0,237000,26.160338,YES
4,South,Laptop,Electronics,92000,1.0,62500.0,250000,36.800000,YES
5,South,Phone,Electronics,75000,2.0,62500.0,250000,30.000000,YES
8,West,Laptop,Electronics,70000,2.0,61250.0,245000,28.571429,YES
9,West,Phone,Electronics,88000,1.0,61250.0,245000,35.918367,YES

In [33]:
top_2_products = top_2_products.sort_values(by= ["region","revenue"],ascending = [True,False])
top_2_products.head()

,region,product,category,revenue,revenue_rank,region_avg_revenue,region_total_revenue,revenue_contribution_pct,above_region_avg
0,North,Laptop,Electronics,85000,1.0,59250.0,237000,35.864979,YES
1,North,Phone,Electronics,62000,2.0,59250.0,237000,26.160338,YES
2,North,Tablet,Electronics,62000,2.0,59250.0,237000,26.160338,YES
4,South,Laptop,Electronics,92000,1.0,62500.0,250000,36.800000,YES
5,South,Phone,Electronics,75000,2.0,62500.0,250000,30.000000,YES