In [1]:
import pandas as pd 

order_df = pd.read_csv("orders.csv")
payment_df = pd.read_csv("payments.csv")
print(order_df.head())
print(payment_df.head())

   order_id customer_id  order_date     product  quantity  order_amount
0      1001        C101  2025-09-01      Laptop         1         75000
1      1002        C102  2025-09-01       Mouse         2          1200
2      1003        C103  2025-09-02    Keyboard         1          1800
3      1004        C104  2025-09-02     Monitor         2         30000
4      1005        C101  2025-09-03  Headphones         1          2500
  payment_id  order_id payment_date payment_method payment_status  amount_paid
0       P001      1001   2025-09-01    Credit Card      Completed        75000
1       P002      1002   2025-09-01            UPI      Completed         1200
2       P003      1003   2025-09-02     Debit Card      Completed         1800
3       P004      1004   2025-09-03            UPI      Completed        30000
4       P005      1005   2025-09-03    Net Banking        Pending         2500

In [2]:
order_df.columns

Index(['order_id', 'customer_id', 'order_date', 'product', 'quantity',
       'order_amount'],
      dtype='object')

In [3]:
payment_df.columns

Index(['payment_id', 'order_id', 'payment_date', 'payment_method',
       'payment_status', 'amount_paid'],
      dtype='object')

In [5]:

payment_df.dtypes

payment_id        object
order_id           int64
payment_date      object
payment_method    object
payment_status    object
amount_paid        int64
dtype: object

In [6]:
order_df.dtypes

order_id         int64
customer_id     object
order_date      object
product         object
quantity         int64
order_amount     int64
dtype: object

In [7]:
order_df[order_df["order_id"].isna()]

Empty DataFrame
Columns: [order_id, customer_id, order_date, product, quantity, order_amount]
Index: []

In [8]:
payment_df[payment_df["order_id"].isna()]

Empty DataFrame
Columns: [payment_id, order_id, payment_date, payment_method, payment_status, amount_paid]
Index: []

In [10]:
order_df[order_df["order_id"].duplicated()]

Empty DataFrame
Columns: [order_id, customer_id, order_date, product, quantity, order_amount]
Index: []

In [11]:
payment_df[payment_df["order_id"].duplicated()]

Empty DataFrame
Columns: [payment_id, order_id, payment_date, payment_method, payment_status, amount_paid]
Index: []

In [40]:
recon = order_df.merge(payment_df,on = "order_id",how= "outer",indicator= True)
print(recon)

    order_id customer_id  order_date     product  quantity  order_amount  \
0       1001        C101  2025-09-01      Laptop       1.0       75000.0
1       1002        C102  2025-09-01       Mouse       2.0        1200.0
2       1003        C103  2025-09-02    Keyboard       1.0        1800.0
3       1004        C104  2025-09-02     Monitor       2.0       30000.0
4       1005        C101  2025-09-03  Headphones       1.0        2500.0
5       1006        C105  2025-09-03      Webcam       1.0        2200.0
6       1007        C106  2025-09-04     Printer       1.0       12000.0
7       1008        C107  2025-09-04         SSD       2.0        8000.0
8       1009        C108  2025-09-05         RAM       2.0        6000.0
9       1010        C109  2025-09-05      Tablet       1.0       18000.0
10      1011        C110  2025-09-06     Speaker       2.0        4000.0
11      1012        C111  2025-09-06      Router       1.0        3500.0
12      1013         NaN         NaN         NaN       NaN           NaN
13      1014         NaN         NaN         NaN       NaN           NaN

   payment_id payment_date payment_method payment_status  amount_paid  \
0        P001   2025-09-01    Credit Card      Completed      75000.0
1        P002   2025-09-01            UPI      Completed       1200.0
2        P003   2025-09-02     Debit Card      Completed       1800.0
3        P004   2025-09-03            UPI      Completed      30000.0
4        P005   2025-09-03    Net Banking        Pending       2500.0
5        P006   2025-09-04            UPI      Completed       2200.0
6         NaN          NaN            NaN            NaN          NaN
7        P007   2025-09-04    Credit Card      Completed       8000.0
8        P008   2025-09-05     Debit Card         Failed       6000.0
9        P009   2025-09-05            UPI      Completed      18000.0
10        NaN          NaN            NaN            NaN          NaN
11        NaN          NaN            NaN            NaN          NaN
12       P010   2025-09-06    Credit Card      Completed       5000.0
13       P011   2025-09-06            UPI      Completed       3500.0

        _merge
0         both
1         both
2         both
3         both
4         both
5         both
6    left_only
7         both
8         both
9         both
10   left_only
11   left_only
12  right_only
13  right_only

In [19]:
matched = order_df.merge(payment_df,on = "order_id",how= "inner")
matched

,order_id,customer_id,order_date,product,quantity,order_amount,payment_id,payment_date,payment_method,payment_status,amount_paid
0,1001,C101,2025-09-01,Laptop,1,75000,P001,2025-09-01,Credit Card,Completed,75000
1,1002,C102,2025-09-01,Mouse,2,1200,P002,2025-09-01,UPI,Completed,1200
2,1003,C103,2025-09-02,Keyboard,1,1800,P003,2025-09-02,Debit Card,Completed,1800
3,1004,C104,2025-09-02,Monitor,2,30000,P004,2025-09-03,UPI,Completed,30000
4,1005,C101,2025-09-03,Headphones,1,2500,P005,2025-09-03,Net Banking,Pending,2500
5,1006,C105,2025-09-03,Webcam,1,2200,P006,2025-09-04,UPI,Completed,2200
6,1008,C107,2025-09-04,SSD,2,8000,P007,2025-09-04,Credit Card,Completed,8000
7,1009,C108,2025-09-05,RAM,2,6000,P008,2025-09-05,Debit Card,Failed,6000
8,1010,C109,2025-09-05,Tablet,1,18000,P009,2025-09-05,UPI,Completed,18000

In [35]:
unpaid_orders = order_df.merge(payment_df,on = "order_id",how = "left",indicator=True)
unpaid_orders = unpaid_orders.loc[unpaid_orders["_merge"] == "left_only"]
print(unpaid_orders)

    order_id customer_id  order_date  product  quantity  order_amount  \
6       1007        C106  2025-09-04  Printer         1         12000
10      1011        C110  2025-09-06  Speaker         2          4000
11      1012        C111  2025-09-06   Router         1          3500

   payment_id payment_date payment_method payment_status  amount_paid  \
6         NaN          NaN            NaN            NaN          NaN
10        NaN          NaN            NaN            NaN          NaN
11        NaN          NaN            NaN            NaN          NaN

       _merge
6   left_only
10  left_only
11  left_only

In [36]:
recon

,order_id,customer_id,order_date,product,quantity,order_amount,payment_id,payment_date,payment_method,payment_status,amount_paid
0,1001,C101,2025-09-01,Laptop,1,75000,P001,2025-09-01,Credit Card,Completed,75000.0
1,1002,C102,2025-09-01,Mouse,2,1200,P002,2025-09-01,UPI,Completed,1200.0
2,1003,C103,2025-09-02,Keyboard,1,1800,P003,2025-09-02,Debit Card,Completed,1800.0
3,1004,C104,2025-09-02,Monitor,2,30000,P004,2025-09-03,UPI,Completed,30000.0
4,1005,C101,2025-09-03,Headphones,1,2500,P005,2025-09-03,Net Banking,Pending,2500.0
5,1006,C105,2025-09-03,Webcam,1,2200,P006,2025-09-04,UPI,Completed,2200.0
6,1007,C106,2025-09-04,Printer,1,12000,NaN,NaN,NaN,NaN,NaN
7,1008,C107,2025-09-04,SSD,2,8000,P007,2025-09-04,Credit Card,Completed,8000.0
8,1009,C108,2025-09-05,RAM,2,6000,P008,2025-09-05,Debit Card,Failed,6000.0
9,1010,C109,2025-09-05,Tablet,1,18000,P009,2025-09-05,UPI,Completed,18000.0
10,1011,C110,2025-09-06,Speaker,2,4000,NaN,NaN,NaN,NaN,NaN
11,1012,C111,2025-09-06,Router,1,3500,NaN,NaN,NaN,NaN,NaN

In [41]:
print(recon.columns)

Index(['order_id', 'customer_id', 'order_date', 'product', 'quantity',
       'order_amount', 'payment_id', 'payment_date', 'payment_method',
       'payment_status', 'amount_paid', '_merge'],
      dtype='object')

In [42]:
orphan_payments = recon.loc[recon["_merge"] == "right_only"]
orphan_payments

,order_id,customer_id,order_date,product,quantity,order_amount,payment_id,payment_date,payment_method,payment_status,amount_paid,_merge
12,1013,NaN,NaN,NaN,NaN,NaN,P010,2025-09-06,Credit Card,Completed,5000.0,right_only
13,1014,NaN,NaN,NaN,NaN,NaN,P011,2025-09-06,UPI,Completed,3500.0,right_only

In [48]:
unmatched_records  = matched[matched["payment_status"] != "Completed"]

In [30]:
payment_df["payment_status"].unique()

array(['Completed', 'Pending', 'Failed'], dtype=object)

In [31]:
recon  = order_df.merge(payment_df,on= "order_id",how= "left",validate="one_to_one")
recon

,order_id,customer_id,order_date,product,quantity,order_amount,payment_id,payment_date,payment_method,payment_status,amount_paid
0,1001,C101,2025-09-01,Laptop,1,75000,P001,2025-09-01,Credit Card,Completed,75000.0
1,1002,C102,2025-09-01,Mouse,2,1200,P002,2025-09-01,UPI,Completed,1200.0
2,1003,C103,2025-09-02,Keyboard,1,1800,P003,2025-09-02,Debit Card,Completed,1800.0
3,1004,C104,2025-09-02,Monitor,2,30000,P004,2025-09-03,UPI,Completed,30000.0
4,1005,C101,2025-09-03,Headphones,1,2500,P005,2025-09-03,Net Banking,Pending,2500.0
5,1006,C105,2025-09-03,Webcam,1,2200,P006,2025-09-04,UPI,Completed,2200.0
6,1007,C106,2025-09-04,Printer,1,12000,NaN,NaN,NaN,NaN,NaN
7,1008,C107,2025-09-04,SSD,2,8000,P007,2025-09-04,Credit Card,Completed,8000.0
8,1009,C108,2025-09-05,RAM,2,6000,P008,2025-09-05,Debit Card,Failed,6000.0
9,1010,C109,2025-09-05,Tablet,1,18000,P009,2025-09-05,UPI,Completed,18000.0
10,1011,C110,2025-09-06,Speaker,2,4000,NaN,NaN,NaN,NaN,NaN
11,1012,C111,2025-09-06,Router,1,3500,NaN,NaN,NaN,NaN,NaN

In [50]:
matched["order_id"].shape[0]

9

In [51]:
unpaid_orders["order_id"].shape[0]

3

In [47]:
orphan_payments["order_id"].count()

2

In [49]:
unmatched_records["order_id"].count()

2