In [33]:
import pandas as pd 

df = pd.read_csv("hospital_claims.csv")
print(df.head())

  claim_id hospital_id patient_id  claim_amount  claim_status    claim_type
0   CLM001        H101      P1001         45000      APPROVED       SURGERY
1   CLM002        H102      P1002         85000       PENDING       SURGERY
2   CLM003        H103      P1003         12000      REJECTED  CONSULTATION
3   CLM004        H101      P1004         95000  UNDER_REVIEW       SURGERY
4   CLM005        H104      P1005         35000      APPROVED    DIAGNOSTIC

In [18]:
print("no. of columns and rows :",df.shape)
print("\n")

print("list of column names and datatypes:\n",df.dtypes)
print("\n")
print("overall_info :")
df.info()

no. of columns and rows : (15, 6)


list of column names and datatypes:
 claim_id        object
hospital_id     object
patient_id      object
claim_amount     int64
claim_status    object
claim_type      object
dtype: object


overall_info :
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   claim_id      15 non-null     object
 1   hospital_id   15 non-null     object
 2   patient_id    15 non-null     object
 3   claim_amount  15 non-null     int64
 4   claim_status  15 non-null     object
 5   claim_type    15 non-null     object
dtypes: int64(1), object(5)
memory usage: 848.0+ bytes

In [35]:
df["claim_amount"] = df["claim_amount"].astype(float)

In [23]:
df[(df["claim_amount"] > 75000) & (df["claim_status"].isin(["PENDING","UNDER_REVIEW"]))]

   claim_id hospital_id patient_id  claim_amount  claim_status claim_type
1    CLM002        H102      P1002         85000       PENDING    SURGERY
3    CLM004        H101      P1004         95000  UNDER_REVIEW    SURGERY
5    CLM006        H102      P1006         78000       PENDING  EMERGENCY
6    CLM007        H105      P1007        150000       PENDING    SURGERY
13   CLM014        H104      P1014        125000  UNDER_REVIEW  EMERGENCY

In [24]:
df[df["claim_amount"].between(50000,100000)]

   claim_id hospital_id patient_id  claim_amount  claim_status  claim_type
1    CLM002        H102      P1002         85000       PENDING     SURGERY
3    CLM004        H101      P1004         95000  UNDER_REVIEW     SURGERY
5    CLM006        H102      P1006         78000       PENDING   EMERGENCY
8    CLM009        H104      P1009         67000      APPROVED   EMERGENCY
10   CLM011        H105      P1011         55000       PENDING  DIAGNOSTIC
11   CLM012        H102      P1012         92000      APPROVED     SURGERY
14   CLM015        H105      P1015         72000      REJECTED     SURGERY

In [25]:
suspicious_claims = df[(df["claim_amount"] > 70000) & (df["claim_status"].isin(["PENDING","REJECTED","UNDER_REVIEW"]))]
suspicious_claims

   claim_id hospital_id patient_id  claim_amount  claim_status claim_type
1    CLM002        H102      P1002         85000       PENDING    SURGERY
3    CLM004        H101      P1004         95000  UNDER_REVIEW    SURGERY
5    CLM006        H102      P1006         78000       PENDING  EMERGENCY
6    CLM007        H105      P1007        150000       PENDING    SURGERY
9    CLM010        H101      P1010        105000      REJECTED    SURGERY
13   CLM014        H104      P1014        125000  UNDER_REVIEW  EMERGENCY
14   CLM015        H105      P1015         72000      REJECTED    SURGERY

In [28]:
suspicious_claims_col = suspicious_claims[["claim_id","hospital_id","patient_id","claim_amount","claim_status"]]
suspicious_claims_col

   claim_id hospital_id patient_id  claim_amount  claim_status
1    CLM002        H102      P1002         85000       PENDING
3    CLM004        H101      P1004         95000  UNDER_REVIEW
5    CLM006        H102      P1006         78000       PENDING
6    CLM007        H105      P1007        150000       PENDING
9    CLM010        H101      P1010        105000      REJECTED
13   CLM014        H104      P1014        125000  UNDER_REVIEW
14   CLM015        H105      P1015         72000      REJECTED

In [ ]:
suspicious_claims = suspicious_claims.sort_values("claim_amount",ascending= False)

   claim_id hospital_id patient_id  claim_amount  claim_status claim_type
6    CLM007        H105      P1007        150000       PENDING    SURGERY
13   CLM014        H104      P1014        125000  UNDER_REVIEW  EMERGENCY
9    CLM010        H101      P1010        105000      REJECTED    SURGERY
3    CLM004        H101      P1004         95000  UNDER_REVIEW    SURGERY
1    CLM002        H102      P1002         85000       PENDING    SURGERY
5    CLM006        H102      P1006         78000       PENDING  EMERGENCY
14   CLM015        H105      P1015         72000      REJECTED    SURGERY

In [34]:
df.nlargest(3,"claim_amount")

   claim_id hospital_id patient_id  claim_amount  claim_status claim_type
6    CLM007        H105      P1007        150000       PENDING    SURGERY
13   CLM014        H104      P1014        125000  UNDER_REVIEW  EMERGENCY
9    CLM010        H101      P1010        105000      REJECTED    SURGERY